-- The Hall of Fame, as data an admin maintains rather than a file a developer
-- edits.
--
-- Until now the page was a TypeScript file, so recording a result meant a pull
-- request. An entry is a dated achievement with a heading, an optional
-- subheading and write-up, and any number of links and photographs.
--
-- NOTE for Phase 3: this takes V12. The Phase 3 playbook's migrations start at
-- V13 -- amendment A1 there has been updated to match.

CREATE TABLE IF NOT EXISTS hall_of_fame_entries (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    heading     VARCHAR(200)  NOT NULL,
    subheading  VARCHAR(300),
    details     TEXT,

    -- A date, not a timestamp. "When" for an achievement is the day it happened,
    -- and a time of day would only invite timezone bugs in the year grouping.
    achieved_on DATE          NOT NULL,

    -- SET NULL, not CASCADE and not a bare reference. The record belongs to the
    -- club, not to the admin who typed it in: deleting that account must neither
    -- delete the achievement nor be blocked by it. The events table made the
    -- second mistake, and it is why clearing test accounts meant clearing events.
    created_by  BIGINT,

    created_at  TIMESTAMP(6)  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP(6)  NOT NULL DEFAULT NOW(),

    PRIMARY KEY (id),
    CONSTRAINT fk_hof_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
);

-- The page lists newest first; the tie-break keeps two entries on the same day
-- in a stable order across requests.
CREATE INDEX IF NOT EXISTS idx_hof_achieved_on ON hall_of_fame_entries (achieved_on DESC, id DESC);

CREATE TABLE IF NOT EXISTS hall_of_fame_links (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    entry_id  BIGINT        NOT NULL,
    label     VARCHAR(100)  NOT NULL,
    url       VARCHAR(512)  NOT NULL,
    -- Explicit order, because "ranklist, then editorial, then photos" is a choice
    -- the admin made and insertion order is not something to rely on.
    position  INTEGER       NOT NULL,

    PRIMARY KEY (id),
    CONSTRAINT fk_hof_links_entry FOREIGN KEY (entry_id) REFERENCES hall_of_fame_entries (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_hof_links_entry ON hall_of_fame_links (entry_id, position);

CREATE TABLE IF NOT EXISTS hall_of_fame_photos (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    entry_id   BIGINT        NOT NULL,
    image_url  VARCHAR(512)  NOT NULL,
    caption    VARCHAR(300),
    position   INTEGER       NOT NULL,

    PRIMARY KEY (id),
    CONSTRAINT fk_hof_photos_entry FOREIGN KEY (entry_id) REFERENCES hall_of_fame_entries (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_hof_photos_entry ON hall_of_fame_photos (entry_id, position);
