-- Phase 3, Stage 0: Codeforces problem metadata, and every problem a member has
-- solved. Stats (Section 1.1), topic strength and practice suggestions all read these.
-- Renamed from V8 per Amendment A1 (V1-V13 taken by Phase 2 and Phase 2.5).

CREATE TABLE IF NOT EXISTS cf_problems (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    -- "1843/C", or "acmsguru/100" for problems with no contestId. A plain UNIQUE on
    -- (contest_id, problem_index) would not work: PostgreSQL treats NULLs as distinct.
    problem_key     VARCHAR(64)  NOT NULL,
    contest_id      INTEGER,
    problemset_name VARCHAR(50),
    problem_index   VARCHAR(10)  NOT NULL,
    name            VARCHAR(255) NOT NULL,
    rating          INTEGER,
    solved_count    INTEGER,     -- from problemset.problems; orders practice suggestions
    PRIMARY KEY (id),
    CONSTRAINT uk_cf_problems_key UNIQUE (problem_key)
);
CREATE INDEX IF NOT EXISTS idx_cf_problems_rating ON cf_problems (rating);

CREATE TABLE IF NOT EXISTS cf_problem_tags (
    problem_id BIGINT      NOT NULL,
    tag        VARCHAR(64) NOT NULL,
    PRIMARY KEY (problem_id, tag),
    CONSTRAINT fk_cf_problem_tags_problem FOREIGN KEY (problem_id) REFERENCES cf_problems (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_cf_problem_tags_tag ON cf_problem_tags (tag);

CREATE TABLE IF NOT EXISTS cf_solves (
    id                     BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id                BIGINT       NOT NULL,
    problem_id             BIGINT       NOT NULL,
    first_ac_at            TIMESTAMP(6) NOT NULL,  -- first accepted submission (D2); stored UTC (D31)
    first_ac_submission_id BIGINT       NOT NULL,
    participant_type       VARCHAR(30)  NOT NULL,  -- CONTESTANT, PRACTICE, VIRTUAL, OUT_OF_COMPETITION, MANAGER
    PRIMARY KEY (id),
    CONSTRAINT uk_cf_solves_user_problem UNIQUE (user_id, problem_id),
    CONSTRAINT fk_cf_solves_user    FOREIGN KEY (user_id)    REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_cf_solves_problem FOREIGN KEY (problem_id) REFERENCES cf_problems (id)
);
CREATE INDEX IF NOT EXISTS idx_cf_solves_user_time ON cf_solves (user_id, first_ac_at);
CREATE INDEX IF NOT EXISTS idx_cf_solves_time      ON cf_solves (first_ac_at);

-- One row per scheduled or admin-triggered sync run. Backs the Sync Health admin tab
-- (Stage 3A) and is the first place to look when a platform starts failing.
CREATE TABLE IF NOT EXISTS sync_runs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    job            VARCHAR(40)   NOT NULL,  -- CF_SUBMISSIONS, LC_TOTALS, EXTERNAL_CONTESTS, ...
    started_at     TIMESTAMP(6)  NOT NULL,  -- UTC (D31)
    finished_at    TIMESTAMP(6),            -- UTC (D31)
    members_ok     INTEGER       NOT NULL DEFAULT 0,
    members_failed INTEGER       NOT NULL DEFAULT 0,
    error_sample   VARCHAR(1000),           -- first failure message; never a full stack trace
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_sync_runs_job_started ON sync_runs (job, started_at);
