-- Phase 3, Stage 0: every Codeforces and LeetCode contest a member entered (D5).
-- Also the source for multi-platform rating charts (O10): new_rating per contest
-- is exact, where weekly_snapshots only samples once a week.
-- All TIMESTAMP columns hold UTC (D31).
-- Renamed from V9 per Amendment A1.

CREATE TABLE IF NOT EXISTS contest_participations (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id             BIGINT       NOT NULL,
    platform            VARCHAR(20)  NOT NULL,
    external_contest_id VARCHAR(64)  NOT NULL,
    contest_name        VARCHAR(255) NOT NULL,
    started_at          TIMESTAMP(6) NOT NULL,  -- UTC (D31)
    rated               BOOLEAN      NOT NULL,
    contest_rank        INTEGER,     -- not "rank": that is a PostgreSQL window function name
    old_rating          INTEGER,
    new_rating          INTEGER,
    PRIMARY KEY (id),
    CONSTRAINT uk_contest_participations       UNIQUE (user_id, platform, external_contest_id),
    CONSTRAINT fk_contest_participations_user  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT contest_participations_platform_check
        CHECK (platform IN ('CODEFORCES', 'LEETCODE'))  -- CodeChef and AtCoder are link only (D9)
);
CREATE INDEX IF NOT EXISTS idx_contest_participations_platform_time ON contest_participations (platform, started_at);
CREATE INDEX IF NOT EXISTS idx_contest_participations_user_time     ON contest_participations (user_id, platform, started_at);
