-- Phase 3, Stage 0: daily LeetCode solved-total baselines. LeetCode has no dated
-- solve history, so period counts subtract a baseline from the live total (D6).
-- Renamed from V10 per Amendment A1.

CREATE TABLE IF NOT EXISTS platform_daily_totals (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT      NOT NULL,
    platform      VARCHAR(20) NOT NULL,
    captured_on   DATE        NOT NULL,  -- the IST calendar date this total belongs to (D1, D6)
    total_solved  INTEGER     NOT NULL,
    easy_solved   INTEGER,
    medium_solved INTEGER,
    hard_solved   INTEGER,
    PRIMARY KEY (id),
    CONSTRAINT uk_platform_daily_totals        UNIQUE (user_id, platform, captured_on),
    CONSTRAINT fk_platform_daily_totals_user   FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT platform_daily_totals_platform_check CHECK (platform IN ('LEETCODE'))
);
