-- Phase 3, Stage 0: LeetCode live totals, sync cursors, email verification and
-- notification preferences on users. Every new column is nullable or defaulted
-- so this migration is backward compatible with a running previous release.
-- Renamed from V11 per Amendment A1.

-- Live LeetCode solved totals, refreshed by every sync (D6). Period math subtracts a baseline.
ALTER TABLE users ADD COLUMN IF NOT EXISTS leetcode_total_solved  INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS leetcode_easy_solved   INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS leetcode_medium_solved INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS leetcode_hard_solved   INTEGER;

-- Incremental sync cursor: highest Codeforces submission id already processed.
-- NULL means this member has never been synced (triggers a full backfill).
ALTER TABLE users ADD COLUMN IF NOT EXISTS cf_last_submission_id  BIGINT;

-- Timestamps of the most recent successful sync per platform (UTC, D31).
ALTER TABLE users ADD COLUMN IF NOT EXISTS cf_synced_at       TIMESTAMP(6);
ALTER TABLE users ADD COLUMN IF NOT EXISTS leetcode_synced_at TIMESTAMP(6);

-- D15 (A2): sign-in is Google-only and university-domain-checked, so every existing
-- account is already implicitly verified. Back-fill to created_at so the service
-- layer never sees a NULL for accounts that predate this migration.
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMP(6);
UPDATE users SET email_verified_at = created_at WHERE email_verified_at IS NULL;

-- Opt-in notification preferences (D29). Both default false (opt-out is the default).
ALTER TABLE users ADD COLUMN IF NOT EXISTS notify_events   BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notify_contests BOOLEAN NOT NULL DEFAULT FALSE;

-- Email verification token table. Kept for Stage 1C (Spring Mail), even though
-- the Google-only flow (A2) means it is never used for the primary sign-in path.
-- A non-null entry here represents a pending token for a secondary verification action.
CREATE TABLE IF NOT EXISTS email_verification_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT       NOT NULL,
    token_hash VARCHAR(64)  NOT NULL,  -- SHA-256 hex. The raw token exists only in the email.
    expires_at TIMESTAMP(6) NOT NULL,  -- UTC (D31)
    used_at    TIMESTAMP(6),           -- UTC (D31); NULL = not yet consumed
    created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    CONSTRAINT uk_email_verification_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_email_verification_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
