-- Phase 3, Stage 0: Overall Aggregated Score (D8), weekly awards (Section 1.5),
-- and practice suggestion skips (Section 1.4).
-- Renamed from V12 per Amendment A1.

-- One row per member; upserted daily at 01:00 IST by Stage 3B (D8).
-- member_scores has no created_at: computed_at serves the same purpose.
CREATE TABLE IF NOT EXISTS member_scores (
    user_id       BIGINT       NOT NULL,
    overall_score INTEGER      NOT NULL,
    rating_score  INTEGER      NOT NULL,
    solved_score  INTEGER      NOT NULL,
    contest_score INTEGER      NOT NULL,
    computed_at   TIMESTAMP(6) NOT NULL,  -- UTC (D31)
    PRIMARY KEY (user_id),
    CONSTRAINT fk_member_scores_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_member_scores_overall ON member_scores (overall_score DESC);

-- One row per award winner per week. Multiple rows per week_start are valid
-- (ties, or different award types). Uniqueness is per (week, type, member).
CREATE TABLE IF NOT EXISTS weekly_awards (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    week_start   DATE         NOT NULL,  -- the Monday (IST, D1) on which the awarded week began
    award_type   VARCHAR(40)  NOT NULL,
    user_id      BIGINT       NOT NULL,
    metric_value INTEGER      NOT NULL,
    platform     VARCHAR(20),            -- non-null for BIGGEST_RATING_JUMP only
    computed_at  TIMESTAMP(6) NOT NULL,  -- UTC (D31)
    computed_by  BIGINT,                 -- NULL = the scheduler; non-null = an admin recompute (audit trail)
    PRIMARY KEY (id),
    CONSTRAINT uk_weekly_awards        UNIQUE (week_start, award_type, user_id),
    CONSTRAINT fk_weekly_awards_user   FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_weekly_awards_by     FOREIGN KEY (computed_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT weekly_awards_type_check
        CHECK (award_type IN ('CODER_OF_THE_WEEK', 'MOST_SOLVED', 'BIGGEST_RATING_JUMP'))
);
CREATE INDEX IF NOT EXISTS idx_weekly_awards_week ON weekly_awards (week_start);

-- A member can permanently hide a practice suggestion. One row per hidden problem.
CREATE TABLE IF NOT EXISTS practice_suggestion_skips (
    user_id    BIGINT       NOT NULL,
    problem_id BIGINT       NOT NULL,
    skipped_at TIMESTAMP(6) NOT NULL,  -- UTC (D31)
    PRIMARY KEY (user_id, problem_id),
    CONSTRAINT fk_practice_skips_user    FOREIGN KEY (user_id)    REFERENCES users (id)        ON DELETE CASCADE,
    CONSTRAINT fk_practice_skips_problem FOREIGN KEY (problem_id) REFERENCES cf_problems (id)  ON DELETE CASCADE
);
