-- Phase 3, Stage 0: club-hosted Codeforces contests, seasons, results and
-- per-problem outcomes. Powers club ranklists (O13), the Championship (O14)
-- and upsolve tracking (P1).
-- Renamed from V13 per Amendment A1. All TIMESTAMP columns hold UTC (D31).

CREATE TABLE IF NOT EXISTS club_seasons (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(100) NOT NULL,
    starts_on  DATE         NOT NULL,
    ends_on    DATE         NOT NULL,
    count_best INTEGER,                 -- NULL = every contest in the season counts (Section 1.3)
    created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    CONSTRAINT club_seasons_dates_check      CHECK (ends_on >= starts_on),
    CONSTRAINT club_seasons_count_best_check CHECK (count_best IS NULL OR count_best > 0)
);

CREATE TABLE IF NOT EXISTS club_contests (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cf_contest_id    INTEGER      NOT NULL,
    season_id        BIGINT,
    kind             VARCHAR(20)  NOT NULL,
    name             VARCHAR(255) NOT NULL,
    starts_at        TIMESTAMP(6) NOT NULL,   -- UTC (D31)
    duration_seconds INTEGER      NOT NULL,
    last_synced_at   TIMESTAMP(6),            -- UTC (D31)
    created_by       BIGINT       NOT NULL,
    created_at       TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    CONSTRAINT uk_club_contests_cf_id       UNIQUE (cf_contest_id),
    CONSTRAINT fk_club_contests_season      FOREIGN KEY (season_id)  REFERENCES club_seasons (id) ON DELETE SET NULL,
    CONSTRAINT fk_club_contests_created_by  FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT club_contests_kind_check     CHECK (kind IN ('GYM', 'MASHUP', 'GROUP', 'OFFICIAL'))
);

CREATE TABLE IF NOT EXISTS club_contest_problems (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    club_contest_id BIGINT       NOT NULL,
    problem_index   VARCHAR(10)  NOT NULL,
    name            VARCHAR(255) NOT NULL,
    rating          INTEGER,
    PRIMARY KEY (id),
    CONSTRAINT uk_club_contest_problems         UNIQUE (club_contest_id, problem_index),
    CONSTRAINT fk_club_contest_problems_contest FOREIGN KEY (club_contest_id) REFERENCES club_contests (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS club_contest_results (
    id              BIGINT         GENERATED BY DEFAULT AS IDENTITY,
    club_contest_id BIGINT         NOT NULL,
    user_id         BIGINT         NOT NULL,
    contest_rank    INTEGER        NOT NULL,   -- rank among club members only (not global CF rank)
    cf_points       NUMERIC(10, 2) NOT NULL,   -- the Codeforces standings score, not championship points
    penalty         INTEGER        NOT NULL,
    solved_count    INTEGER        NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_club_contest_results         UNIQUE (club_contest_id, user_id),
    CONSTRAINT fk_club_contest_results_contest FOREIGN KEY (club_contest_id) REFERENCES club_contests (id) ON DELETE CASCADE,
    CONSTRAINT fk_club_contest_results_user    FOREIGN KEY (user_id)         REFERENCES users (id)         ON DELETE CASCADE
);

-- Per-problem outcome within a club contest result.
-- solved_in_contest distinguishes a live solve from an upsolve (D12).
CREATE TABLE IF NOT EXISTS club_contest_problem_results (
    result_id         BIGINT  NOT NULL,
    problem_id        BIGINT  NOT NULL,
    solved_in_contest BOOLEAN NOT NULL,
    PRIMARY KEY (result_id, problem_id),
    CONSTRAINT fk_ccpr_result  FOREIGN KEY (result_id)  REFERENCES club_contest_results   (id) ON DELETE CASCADE,
    CONSTRAINT fk_ccpr_problem FOREIGN KEY (problem_id) REFERENCES club_contest_problems  (id) ON DELETE CASCADE
);
