-- Baseline schema for Phase 1.
--
-- Generated from the JPA entities via Hibernate's PostgreSQL dialect, so it
-- matches exactly what `ddl-auto: validate` expects at startup. Do not hand-edit
-- to add columns: create a new V2__*.sql instead, or production will fail
-- validation with no forward path.
--
-- Existing deployments already have these tables. `baseline-on-migrate: true`
-- tells Flyway to record this version as already applied rather than replaying
-- it against a populated database.

CREATE TABLE IF NOT EXISTS users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name              VARCHAR(255) NOT NULL,
    email             VARCHAR(255) NOT NULL UNIQUE,
    password          VARCHAR(255) NOT NULL,
    codeforces_handle VARCHAR(255) UNIQUE,
    rating            INTEGER,
    role              VARCHAR(255) NOT NULL CHECK (role IN ('ROLE_USER', 'ROLE_ADMIN')),
    created_at        TIMESTAMP(6) NOT NULL,
    updated_at        TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS blog_posts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title       VARCHAR(255) NOT NULL,
    slug        VARCHAR(255) NOT NULL UNIQUE,
    content     TEXT NOT NULL,
    author_name VARCHAR(255) NOT NULL,
    tags        VARCHAR(255),
    published   BOOLEAN,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id)
);

-- The leaderboard sorts on rating and the sync looks members up by handle;
-- both are required by the performance criteria in the Phase 1 playbook.
CREATE INDEX IF NOT EXISTS idx_rating ON users (rating);
CREATE INDEX IF NOT EXISTS idx_codeforces_handle ON users (codeforces_handle);
CREATE INDEX IF NOT EXISTS idx_blog_slug ON blog_posts (slug);
CREATE INDEX IF NOT EXISTS idx_blog_published ON blog_posts (published);
