-- Phase 3, Stage 0: member-written posts with review workflow (D18), and
-- comments (D19). Migrates the existing boolean published flag to a status
-- enum column so the two can coexist during rollout.
-- Renamed from V14 per Amendment A1.

-- Add workflow columns. All nullable or defaulted so existing rows are untouched.
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS status       VARCHAR(20) NOT NULL DEFAULT 'DRAFT';
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS author_id    BIGINT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS reviewer_id  BIGINT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS review_note  VARCHAR(500);
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMP(6);  -- UTC (D31)
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS published_at TIMESTAMP(6);  -- UTC (D31)

-- Map the legacy boolean. V1 allows published to be NULL, and the public endpoints
-- only ever served "published = true" (findByPublishedTrue). A NULL row is therefore
-- not public today, and must NOT become PUBLISHED here.
UPDATE blog_posts SET status = CASE WHEN published IS TRUE THEN 'PUBLISHED' ELSE 'DRAFT' END;
UPDATE blog_posts SET published_at = created_at WHERE status = 'PUBLISHED' AND published_at IS NULL;

ALTER TABLE blog_posts ADD CONSTRAINT blog_posts_status_check
    CHECK (status IN ('DRAFT', 'PENDING_REVIEW', 'PUBLISHED', 'REJECTED'));
ALTER TABLE blog_posts ADD CONSTRAINT fk_blog_posts_author
    FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE blog_posts ADD CONSTRAINT fk_blog_posts_reviewer
    FOREIGN KEY (reviewer_id) REFERENCES users (id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_blog_posts_status_published ON blog_posts (status, published_at);

-- The published column is intentionally kept. BlogService keeps it in step with
-- status in @PrePersist/@PreUpdate, so a backend release running the previous code
-- reads correct values during a rolling deploy. Drop it in a Phase 4 cleanup.

CREATE TABLE IF NOT EXISTS blog_comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    post_id    BIGINT        NOT NULL,
    user_id    BIGINT        NOT NULL,
    parent_id  BIGINT,                  -- one level of replies; deeper nesting refused in the service
    body       VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP(6)  NOT NULL DEFAULT NOW(),  -- UTC (D31)
    updated_at TIMESTAMP(6),                          -- UTC (D31); set on the 15-min edit window
    deleted_at TIMESTAMP(6),                          -- soft delete; rendered as "[deleted]"
    PRIMARY KEY (id),
    CONSTRAINT fk_blog_comments_post   FOREIGN KEY (post_id)   REFERENCES blog_posts    (id) ON DELETE CASCADE,
    CONSTRAINT fk_blog_comments_user   FOREIGN KEY (user_id)   REFERENCES users         (id) ON DELETE CASCADE,
    CONSTRAINT fk_blog_comments_parent FOREIGN KEY (parent_id) REFERENCES blog_comments (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_blog_comments_post_time ON blog_comments (post_id, created_at);
