-- Phase 3, Stage 0: member RSVPs (D13), external contests for the calendar (D26),
-- and the idempotency log for reminder emails (D29).
-- Renamed from V15 per Amendment A1. All TIMESTAMP columns hold UTC (D31).

-- Optional capacity cap per event. NULL = unlimited.
ALTER TABLE events ADD COLUMN IF NOT EXISTS capacity INTEGER;
ALTER TABLE events ADD CONSTRAINT events_capacity_check CHECK (capacity IS NULL OR capacity > 0);

-- Flag to hide the podium section on the event details page.
ALTER TABLE events ADD COLUMN IF NOT EXISTS hide_podium BOOLEAN NOT NULL DEFAULT FALSE;

-- A member's own intent to attend an event (D13). Distinct from admin-marked attendance.
CREATE TABLE IF NOT EXISTS event_registrations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_id      BIGINT       NOT NULL,
    user_id       BIGINT       NOT NULL,
    registered_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),  -- UTC (D31)
    PRIMARY KEY (id),
    CONSTRAINT uk_event_registrations       UNIQUE (event_id, user_id),
    CONSTRAINT fk_event_registrations_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_event_registrations_user  FOREIGN KEY (user_id)  REFERENCES users  (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_event_registrations_event ON event_registrations (event_id);

-- External contest schedule fetched from each platform (D26). Synced every 6 hours.
-- calendar/entity uses ContestPlatform which includes CODECHEF and ATCODER for
-- calendar display even though their member stats are link-only (D9).
CREATE TABLE IF NOT EXISTS external_contests (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    platform         VARCHAR(20)  NOT NULL,
    external_id      VARCHAR(100) NOT NULL,
    name             VARCHAR(255) NOT NULL,
    url              VARCHAR(512) NOT NULL,
    starts_at        TIMESTAMP(6) NOT NULL,   -- UTC (D31)
    duration_seconds INTEGER      NOT NULL,
    synced_at        TIMESTAMP(6) NOT NULL,   -- UTC (D31)
    PRIMARY KEY (id),
    CONSTRAINT uk_external_contests          UNIQUE (platform, external_id),
    CONSTRAINT external_contests_platform_check
        CHECK (platform IN ('CODEFORCES', 'LEETCODE', 'CODECHEF', 'ATCODER'))
);
CREATE INDEX IF NOT EXISTS idx_external_contests_start ON external_contests (starts_at);

-- Prevents a re-run cron from emailing the same person twice (D29).
-- The unique constraint on (user_id, kind, ref_key) is the idempotency gate.
CREATE TABLE IF NOT EXISTS reminder_log (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT       NOT NULL,
    kind    VARCHAR(30)  NOT NULL,
    ref_key VARCHAR(120) NOT NULL,  -- "event:42" or "digest:2026-11-03"
    sent_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),  -- UTC (D31)
    PRIMARY KEY (id),
    CONSTRAINT uk_reminder_log      UNIQUE (user_id, kind, ref_key),
    CONSTRAINT fk_reminder_log_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT reminder_log_kind_check CHECK (kind IN ('EVENT_24H', 'CONTEST_DIGEST'))
);
