CREATE TABLE compete_matches (
    id VARCHAR(255) NOT NULL,
    mode VARCHAR(255) NOT NULL,
    start_time TIMESTAMP(6) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    timeout_minutes INTEGER,
    replace_increment INTEGER,
    grid_size INTEGER,
    last_polled_at TIMESTAMP(6) NOT NULL,
    min_rating INTEGER,
    max_rating INTEGER,
    show_ratings BOOLEAN NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE compete_problems (
    contest_id INTEGER NOT NULL,
    index VARCHAR(255) NOT NULL,
    match_id VARCHAR(255) NOT NULL,
    rating INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    max_points INTEGER,
    position INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    PRIMARY KEY (contest_id, index, match_id),
    CONSTRAINT fk_compete_problems_match FOREIGN KEY (match_id) REFERENCES compete_matches (id)
);

CREATE TABLE compete_teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    color VARCHAR(255) NOT NULL,
    match_id VARCHAR(255),
    PRIMARY KEY (id),
    CONSTRAINT fk_compete_teams_match FOREIGN KEY (match_id) REFERENCES compete_matches (id)
);

CREATE TABLE compete_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    handle VARCHAR(255) NOT NULL,
    team_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_compete_members_team FOREIGN KEY (team_id) REFERENCES compete_teams (id)
);

CREATE TABLE compete_solve_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    handle VARCHAR(255) NOT NULL,
    team VARCHAR(255) NOT NULL,
    contest_id INTEGER NOT NULL,
    index VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP(6) NOT NULL,
    score INTEGER,
    match_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_compete_solve_logs_match FOREIGN KEY (match_id) REFERENCES compete_matches (id),
    CONSTRAINT fk_compete_solve_logs_problem FOREIGN KEY (contest_id, index, match_id) REFERENCES compete_problems (contest_id, index, match_id)
);
