-- Phase 2, Stage 0: club events (workshops, contests, sessions).
--
-- Identity columns use `BIGINT GENERATED BY DEFAULT AS IDENTITY` rather than
-- BIGSERIAL to match V1__init.sql. The two are equivalent to Hibernate's
-- GenerationType.IDENTITY; the identity form is the SQL standard one and keeps
-- the whole schema consistent.

CREATE TABLE IF NOT EXISTS events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title           VARCHAR(255) NOT NULL,
    description     TEXT,
    event_date      TIMESTAMP(6) NOT NULL,
    location        VARCHAR(255) NOT NULL,
    -- Three states rather than an is_active boolean:
    --   UPCOMING  -- public, accepting attendance
    --   COMPLETED -- public, read-only, photo gallery shown
    --   CANCELLED -- hidden from public listings
    -- Events are never hard-deleted, which preserves attendance and gallery
    -- history (Section 1, "Soft delete for events").
    status          VARCHAR(20) NOT NULL DEFAULT 'UPCOMING',
    cover_image_url VARCHAR(512),
    created_by      BIGINT NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    CONSTRAINT fk_events_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT events_status_check CHECK (status IN ('UPCOMING', 'COMPLETED', 'CANCELLED'))
);

-- The two public listings (/api/events/upcoming and /api/events/completed)
-- both filter on status and order by date.
CREATE INDEX IF NOT EXISTS idx_events_status ON events (status);
CREATE INDEX IF NOT EXISTS idx_events_event_date ON events (event_date);
