-- Phase 2, Stage 0: official attendance record, written by admins only.
--
-- Attendance is an official club record, so students cannot self-register --
-- an admin looks a member up by ID and adds them (Section 1).

CREATE TABLE IF NOT EXISTS event_attendees (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_id BIGINT NOT NULL,
    user_id  BIGINT NOT NULL,
    -- Which admin added this student. Kept for auditability: attendance
    -- affects club standing, so every row is attributable.
    added_by BIGINT NOT NULL,
    added_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    CONSTRAINT fk_event_attendees_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_event_attendees_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_event_attendees_added_by FOREIGN KEY (added_by) REFERENCES users (id),
    -- Enforced at the database, not only in the service: two admins adding the
    -- same student concurrently would both pass a service-layer existence check.
    CONSTRAINT uk_event_attendees_event_user UNIQUE (event_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_event_attendees_event ON event_attendees (event_id);
CREATE INDEX IF NOT EXISTS idx_event_attendees_user ON event_attendees (user_id);
