-- Phase 2, Stage 0: photo gallery for completed events.
--
-- Only the Cloudinary secure URL is stored. Images never enter PostgreSQL as
-- binary -- uploads go browser -> Cloudinary directly via the Upload Widget,
-- and the backend records the returned string.

CREATE TABLE IF NOT EXISTS event_photos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_id    BIGINT NOT NULL,
    image_url   VARCHAR(512) NOT NULL,
    caption     VARCHAR(255),
    uploaded_by BIGINT NOT NULL,
    uploaded_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    CONSTRAINT fk_event_photos_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_event_photos_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users (id)
);

-- The public event detail page loads every photo for one event.
CREATE INDEX IF NOT EXISTS idx_event_photos_event ON event_photos (event_id);
