-- Phase 2, Stage 0: batch-wise group photos of club members.
--
-- Deliberately has NO foreign key to events or users-as-subject: these are
-- group photos of a batch ("Batch 2023 - Inauguration Day"), distinct from the
-- individual avatar_url on `users`.

CREATE TABLE IF NOT EXISTS member_gallery (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    batch_year  INTEGER NOT NULL,
    image_url   VARCHAR(512) NOT NULL,
    caption     VARCHAR(255),
    uploaded_by BIGINT NOT NULL,
    uploaded_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    CONSTRAINT fk_member_gallery_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users (id)
);

-- Drives both the batch filter and the DISTINCT batch_year query behind the
-- frontend's year dropdown.
CREATE INDEX IF NOT EXISTS idx_member_gallery_batch_year ON member_gallery (batch_year);
