-- Phase 2, Stage 0: weekly rating history, powering the profile rating charts.
--
-- The Monday cron snapshots the rating values ALREADY stored on `users`; it
-- does not re-fetch from Codeforces or LeetCode. That keeps the job free of
-- external-API failure modes -- a platform outage costs one flat week in the
-- chart, never a failed job or a partial write.
--
-- `platform` is a plain VARCHAR rather than a Java enum, matching the
-- WeeklySnapshot entity: the set is closed by the CHECK constraint below.

CREATE TABLE IF NOT EXISTS weekly_snapshots (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT NOT NULL,
    platform    VARCHAR(20) NOT NULL,
    rating      INTEGER NOT NULL,
    recorded_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    CONSTRAINT fk_weekly_snapshots_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT weekly_snapshots_platform_check CHECK (platform IN ('CODEFORCES', 'LEETCODE'))
);

-- Every read is "one user, one platform, ordered by date" -- a composite index
-- serves that directly. recorded_at is included so the ORDER BY is satisfied
-- from the index rather than a sort.
CREATE INDEX IF NOT EXISTS idx_weekly_snapshots_user_platform
    ON weekly_snapshots (user_id, platform, recorded_at);
