spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cpclub_db
    username: cpclub_user
    password: cpclub_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false
