import type { Member } from "@/types/api";

export const memberGroups = [
  "Everyone",
  "Core team",
  "Associate team",
  "Batch representatives",
  "Students",
] as const;

export const members: Member[] = [
  // ── 👑 LEADERSHIP (2) ──
  {
    name: "Sumeet Verma",
    initials: "SV",
    batch: "B.Tech ’26",
    degree: "B.Tech ICT",
    gradYear: "2026",
    group: "Core team",
    role: "Convenor",
    clubRoleCategory: "Leadership",
    codeforcesHandle: "Sumeet.Verma",
    rating: 2502,
    solvedCount: 1289,
    contestCount: 42,
    cf: "grandmaster",
    isActive: true,
    about: "Club Lead & Grandmaster. Organizing campus contests and leading the ICPC training initiative.",
    isWebDev: true,
    devRole: "Platform Architect & Full-Stack Lead",
    githubUrl: "https://github.com/SumeetVerma",
    linkedinUrl: "https://linkedin.com/in/sumeetverma",
  },
  {
    name: "Preet Sheth",
    initials: "PS",
    batch: "B.Tech ’26",
    degree: "B.Tech ICT",
    gradYear: "2026",
    group: "Core team",
    role: "Deputy Convenor",
    clubRoleCategory: "Leadership",
    codeforcesHandle: "Preet_Sheth",
    rating: 2210,
    solvedCount: 1042,
    contestCount: 38,
    cf: "master",
    isActive: true,
    about: "Deputy Lead & Master. Overseeing weekly contests and advanced data structures workshops.",
    isWebDev: true,
    devRole: "UI/UX & Frontend Lead",
    githubUrl: "https://github.com/PreetSheth",
    linkedinUrl: "https://linkedin.com/in/preetsheth",
  },

  // ── ⚡ CORE TEAM (4) ──
  {
    name: "Jalp Patel",
    initials: "JP",
    batch: "B.Tech ’27",
    degree: "B.Tech ICT",
    gradYear: "2027",
    group: "Core team",
    role: "Core Member (Problem Setter)",
    clubRoleCategory: "Core",
    codeforcesHandle: "jalp_p",
    rating: 1990,
    solvedCount: 915,
    contestCount: 29,
    cf: "candidate",
    isActive: true,
    about: "Head Problem Setter for Code Mutant and Intra-DAU contests.",
  },
  {
    name: "Arjun Mehta",
    initials: "AM",
    batch: "B.Tech ’26",
    degree: "B.Tech MnC",
    gradYear: "2026",
    group: "Core team",
    role: "Core Member (Contest Operations)",
    clubRoleCategory: "Core",
    codeforcesHandle: "arjun_bitset",
    rating: 2050,
    solvedCount: 610,
    contestCount: 25,
    cf: "master",
    isActive: true,
    about: "Managing contest logistics, platform integration, and leaderboard sync.",
  },
  {
    name: "Meher Singh",
    initials: "MS",
    batch: "B.Tech ’27",
    degree: "B.Tech ICT",
    gradYear: "2027",
    group: "Core team",
    role: "Core Member (Editorials Lead)",
    clubRoleCategory: "Core",
    codeforcesHandle: "meher_solves",
    rating: 1890,
    solvedCount: 810,
    contestCount: 27,
    cf: "candidate",
    isActive: true,
    about: "Writing detailed problem editorials and mentoring junior competitive programmers.",
  },
  {
    name: "T. Nair",
    initials: "TN",
    batch: "B.Tech ’26",
    degree: "B.Tech CS",
    gradYear: "2026",
    group: "Core team",
    role: "Core Member (Tech Lead)",
    clubRoleCategory: "Core",
    codeforcesHandle: "tnair_cp",
    rating: 2115,
    solvedCount: 940,
    contestCount: 31,
    cf: "master",
    isActive: true,
    about: "Leading technical infrastructure and Codeforces API integration.",
    isWebDev: true,
    devRole: "Backend & API Systems Developer",
    githubUrl: "https://github.com/TNair",
    linkedinUrl: "https://linkedin.com/in/tnair",
  },

  // ── ◈ ASSOCIATE CORE (6) ──
  {
    name: "King-T",
    initials: "KT",
    batch: "B.Tech ’28",
    degree: "B.Tech ICT",
    gradYear: "2028",
    group: "Associate team",
    role: "Associate Core Member",
    clubRoleCategory: "Associate Core",
    codeforcesHandle: "King_T",
    rating: 1639,
    solvedCount: 654,
    contestCount: 24,
    cf: "expert",
    isActive: true,
    about: "Associate lead for weekend sprints and beginner problem solving sessions.",
  },
  {
    name: "Rohan Gupta",
    initials: "RG",
    batch: "B.Tech ’27",
    degree: "B.Tech MnC",
    gradYear: "2027",
    group: "Associate team",
    role: "Associate Core Member",
    clubRoleCategory: "Associate Core",
    codeforcesHandle: "rohan_dp",
    rating: 1750,
    solvedCount: 780,
    contestCount: 31,
    cf: "expert",
    isActive: true,
    about: "Focusing on DP and Graph algorithms workshops.",
  },
  {
    name: "K. Verma",
    initials: "KV",
    batch: "B.Tech ’28",
    degree: "B.Tech ICT",
    gradYear: "2028",
    group: "Associate team",
    role: "Associate Core Member",
    clubRoleCategory: "Associate Core",
    codeforcesHandle: "kverma_algo",
    rating: 1680,
    solvedCount: 540,
    contestCount: 19,
    cf: "expert",
    isActive: true,
    about: "Organizing beginner C++ and STL workshops.",
    isWebDev: true,
    devRole: "Auth & Directory Developer",
    githubUrl: "https://github.com/KVerma",
    linkedinUrl: "https://linkedin.com/in/kverma",
  },
  {
    name: "P. Joshi",
    initials: "PJ",
    batch: "B.Tech ’28",
    degree: "B.Tech ICT",
    gradYear: "2028",
    group: "Associate team",
    role: "Associate Core Member",
    clubRoleCategory: "Associate Core",
    codeforcesHandle: "pjoshi_code",
    rating: 1610,
    solvedCount: 490,
    contestCount: 18,
    cf: "expert",
    isActive: true,
    about: "Handling event registrations and Discord community engagement.",
  },
  {
    name: "S. Iyer",
    initials: "SI",
    batch: "M.Tech ’26",
    degree: "M.Tech CS",
    gradYear: "2026",
    group: "Associate team",
    role: "Associate Core Member",
    clubRoleCategory: "Associate Core",
    codeforcesHandle: "siyer_math",
    rating: 1540,
    solvedCount: 420,
    contestCount: 15,
    cf: "specialist",
    isActive: false,
    about: "Specializing in Number Theory and Combinatorics.",
  },
  {
    name: "A. Sharma",
    initials: "AS",
    batch: "B.Tech ’28",
    degree: "B.Tech ICT",
    gradYear: "2028",
    group: "Associate team",
    role: "Associate Core Member",
    clubRoleCategory: "Associate Core",
    codeforcesHandle: "asharma_cp",
    rating: 1590,
    solvedCount: 460,
    contestCount: 17,
    cf: "specialist",
    isActive: true,
    about: "Managing practice sets and editorials.",
  },

  // ── 🎓 BATCH REPRESENTATIVES (12) ──
  {
    name: "Alice Sharma",
    initials: "AS",
    batch: "B.Tech ’28",
    degree: "B.Tech ICT",
    gradYear: "2028",
    group: "Batch representatives",
    role: "Batch Representative ('28)",
    clubRoleCategory: "Batch Representative",
    codeforcesHandle: "Alice",
    rating: 1447,
    solvedCount: 512,
    contestCount: 18,
    cf: "specialist",
    isActive: true,
    about: "Batch of '28 representative. Connecting 2nd year students with club activities.",
  },
  {
    name: "N. Desai",
    initials: "ND",
    batch: "B.Tech ’28",
    degree: "B.Tech ICT",
    gradYear: "2028",
    group: "Batch representatives",
    role: "Batch Representative ('28)",
    clubRoleCategory: "Batch Representative",
    codeforcesHandle: "ndesai_rep",
    rating: 1490,
    solvedCount: 480,
    contestCount: 16,
    cf: "specialist",
    isActive: true,
    about: "2nd year batch rep and website design contributor.",
    isWebDev: true,
    devRole: "Design & Frontend Engineer",
    githubUrl: "https://github.com/NDesai",
    linkedinUrl: "https://linkedin.com/in/ndesai",
  },
  {
    name: "R. Shah",
    initials: "RS",
    batch: "B.Tech ’29",
    degree: "B.Tech ICT",
    gradYear: "2029",
    group: "Batch representatives",
    role: "Batch Representative ('29)",
    clubRoleCategory: "Batch Representative",
    codeforcesHandle: "rshah_29",
    rating: 1240,
    solvedCount: 290,
    contestCount: 10,
    cf: "pupil",
    isActive: true,
    about: "Freshman batch rep helping 1st years get started with competitive programming.",
    isWebDev: true,
    devRole: "Leaderboard & Codeforces Sync Engineer",
    githubUrl: "https://github.com/RShah",
    linkedinUrl: "https://linkedin.com/in/rshah",
  },
  {
    name: "V. Patel",
    initials: "VP",
    batch: "B.Tech ’27",
    degree: "B.Tech MnC",
    gradYear: "2027",
    group: "Batch representatives",
    role: "Batch Representative ('27)",
    clubRoleCategory: "Batch Representative",
    codeforcesHandle: "vpatel_27",
    rating: 1510,
    solvedCount: 430,
    contestCount: 14,
    cf: "specialist",
    isActive: true,
    about: "3rd year representative for Mathematics & Computing batch.",
  },
  {
    name: "M. Choudhary",
    initials: "MC",
    batch: "B.Tech ’26",
    degree: "B.Tech ICT",
    gradYear: "2026",
    group: "Batch representatives",
    role: "Batch Representative ('26)",
    clubRoleCategory: "Batch Representative",
    codeforcesHandle: "mchoudhary",
    rating: 1580,
    solvedCount: 510,
    contestCount: 20,
    cf: "specialist",
    isActive: true,
    about: "Senior batch rep helping final year students prepare for ICPC.",
  },
  {
    name: "H. Trivedi",
    initials: "HT",
    batch: "B.Tech ’29",
    degree: "B.Tech ICT",
    gradYear: "2029",
    group: "Batch representatives",
    role: "Batch Representative ('29)",
    clubRoleCategory: "Batch Representative",
    codeforcesHandle: "htrivedi_fresh",
    rating: 1210,
    solvedCount: 240,
    contestCount: 8,
    cf: "pupil",
    isActive: true,
    about: "1st year rep coordinating induction events.",
  },
  {
    name: "D. Solanki",
    initials: "DS",
    batch: "B.Tech ’28",
    degree: "B.Tech MnC",
    gradYear: "2028",
    group: "Batch representatives",
    role: "Batch Representative ('28)",
    clubRoleCategory: "Batch Representative",
    codeforcesHandle: "dsolanki_rep",
    rating: 1390,
    solvedCount: 360,
    contestCount: 12,
    cf: "pupil",
    isActive: true,
    about: "2nd year MnC batch rep.",
  },
  {
    name: "P. Parikh",
    initials: "PP",
    batch: "B.Tech ’27",
    degree: "B.Tech ICT",
    gradYear: "2027",
    group: "Batch representatives",
    role: "Batch Representative ('27)",
    clubRoleCategory: "Batch Representative",
    codeforcesHandle: "pparikh_27",
    rating: 1450,
    solvedCount: 400,
    contestCount: 15,
    cf: "specialist",
    isActive: true,
    about: "3rd year ICT batch rep.",
  },
  {
    name: "K. Bhatt",
    initials: "KB",
    batch: "B.Tech ’29",
    degree: "B.Tech ICT",
    gradYear: "2029",
    group: "Batch representatives",
    role: "Batch Representative ('29)",
    clubRoleCategory: "Batch Representative",
    codeforcesHandle: "kbhatt_cp",
    rating: 1180,
    solvedCount: 190,
    contestCount: 6,
    cf: "newbie",
    isActive: true,
    about: "Freshman outreach rep.",
  },
  {
    name: "S. Trivedi",
    initials: "ST",
    batch: "B.Tech ’28",
    degree: "B.Tech ICT",
    gradYear: "2028",
    group: "Batch representatives",
    role: "Batch Representative ('28)",
    clubRoleCategory: "Batch Representative",
    codeforcesHandle: "strivedi_28",
    rating: 1320,
    solvedCount: 310,
    contestCount: 11,
    cf: "pupil",
    isActive: true,
    about: "2nd year ICT batch rep.",
  },
  {
    name: "A. Joshi",
    initials: "AJ",
    batch: "B.Tech ’26",
    degree: "B.Tech ICT",
    gradYear: "2026",
    group: "Batch representatives",
    role: "Batch Representative ('26)",
    clubRoleCategory: "Batch Representative",
    codeforcesHandle: "ajoshi_sr",
    rating: 1620,
    solvedCount: 580,
    contestCount: 22,
    cf: "expert",
    isActive: true,
    about: "Senior batch rep.",
  },
  {
    name: "R. Contractor",
    initials: "RC",
    batch: "B.Tech ’29",
    degree: "B.Tech MnC",
    gradYear: "2029",
    group: "Batch representatives",
    role: "Batch Representative ('29)",
    clubRoleCategory: "Batch Representative",
    codeforcesHandle: "rcontractor",
    rating: 1150,
    solvedCount: 160,
    contestCount: 5,
    cf: "newbie",
    isActive: true,
    about: "1st year MnC batch rep.",
  },
];

export const credits = [
  { years: "2024–26", name: "N. Desai", initials: "ND", work: "Design and front-end build of this site" },
  { years: "2024–26", name: "R. Shah", initials: "RS", work: "Codeforces sync and leaderboard service" },
  { years: "2024–26", name: "K. Verma", initials: "KV", work: "Auth, profiles, and member directory" },
];
